[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "redactor"
version = "0.0.1"
description = "Redaction System"
readme = "readme.md"
requires-python = ">=3.13"
dependencies = [
    "azure-ai-vision-imageanalysis>=1.0.0",
    "azure-functions>=2.2.0",
    "azure-identity>=1.25.3",
    "azure-monitor-opentelemetry>=1.8.9",
    "azure-storage-blob>=12.30.0",
    "click>=8.1.0",
    "langdetect>=1.0.9",
    "langchain>=1.3.14",
    "langchain-text-splitters>=1.1.2",
    "openai>=2.50.0",
    "pydantic>=2.12.5",
    "pillow>=12.3.0",
    "pyyaml>=6.0.3",
    "tiktoken>=0.13.0",
    "pytest>=9.1.1",
    "azure-functions-durable>=1.4.0",
    "azure-servicebus>=7.14.3",
    "coverage>=7.15.2",
    "filelock>=3.32.2",
    "pre-commit>=4.5.1",
    "python-dotenv>=1.2.2",
    "pymupdf>=1.28.0",
    "pytest-xdist>=3.8.0",
    "pytest-cov>=7.1.0",
    "pytest-rerunfailures>=16.4",
    "ruff>=0.16.0",
    "unidecode>=1.4.0",
    "strenum>=0.4.15",
    "numpy>=2.5.1",
]
classifiers = [
    "Programming Language :: Python :: 3.13",
]
license = "MIT"
license-files = ["LICENSE"]

[project.optional-dependencies]
dev = [
    "coverage",
    "mock",
    "myst-parser",
    "pre-commit",
    "pytest",
    "pytest-xdist",
    "pytest-cov",
    "ruff",
    "toml",
]

[tool.setuptools.packages.find]
where = ["redactor"]

# `coverage` configurations
[tool.coverage.run]
source = [
    "./"
]

[tool.coverage.report]
exclude_lines = [
    "if __name__ == .__main__.:"
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
    
[tool.ruff.lint.isort]
known-first-party = ["core", "test", "config"]

# `bandit' configurations
[tool.bandit]
exclude_dirs = ["redactor/test"]
skips = []